// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadDemo(arg1:string):Promise<string>;

export function ParseFileName(arg1:string):Promise<string>;
