// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadDemo(arg1) {
  return window['go']['main']['App']['DownloadDemo'](arg1);
}

export function ParseFileName(arg1) {
  return window['go']['main']['App']['ParseFileName'](arg1);
}
